config/routes.rb
Rails.application.routes.draw do
  get '/users/dashboard', to: 'users#dashboard'
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:show, :edit, :update]
  resources :lessons, only: [:create, :edit, :update, :delete]
  resources :lessons do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  validates_presence_of :name, :flag
  has_many :language_skills
  has_many :lessons
  has_many :users, through: :language_skills
end

app/models/language_skill.rb
class LanguageSkill < ApplicationRecord
  belongs_to :user
  belongs_to :language
  validates_presence_of :user, :language
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to  :teacher, class_name: "User"
  belongs_to  :student, class_name: "User"
  belongs_to  :language
  has_many :reviews
  STATE = %w[confirmed pending completed cancelled]
  validates :status, inclusion: { in: STATE }
  validates_presence_of :date, :location, :teacher, :student, :language
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  validates_presence_of :title
  has_many :user_qualifications
  has_many :users, through: :user_qualifications
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :lesson
  validates :rating, inclusion: {in: [0, 1, 2, 3, 4, 5]}
  validates_presence_of :content, :rating, :lesson
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lessons, foreign_key: "student_id"
  has_many :commitments, class_name: "Lesson", foreign_key: "teacher_id"
  has_many :reviews, through: :commitments
  has_many :user_qualifications
  has_many :qualifications, through: :user_qualifications
  has_many :language_skills
  has_many :languages, through: :language_skills
  has_one_attached :photo
  validates_presence_of :first_name, :last_name

  def rating
    return false if reviews.count.zero?

    self.reviews.reduce(0) {|acum, review| acum + review.rating } / reviews.count.to_f
  end

  geocoded_by :location
  after_validation :geocode

end

app/models/user_qualification.rb
class UserQualification < ApplicationRecord
  belongs_to :user
  belongs_to :qualification
  validates_presence_of :user, :qualification
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :is_teacher])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def create
    teacher = User.find(params[:lesson][:teacher_id])
    student = User.find(params[:lesson][:student_id])
    @lesson = Lesson.new(lesson_params)
    @lesson.teacher = teacher
    @lesson.student = student
    authorize @lesson
    if @lesson.save
      flash[:alert] = 'Lesson booked!'
    else
      flash[:alert] = 'There was a problem with your lesson.'
    end
    redirect_to users_dashboard_path
  end

  def edit
    authorize @lesson
  end

  def update
    lesson = Lesson.find(params[:id])
    authorize lesson
    lesson.update(status: params[:lesson][:status])
    redirect_to users_dashboard_path
  end

  def destroy
    lesson = Lesson.find(params[:id].to_i)
    authorize lesson
    lesson.destroy
    redirect_to users_dashboard_path
  end

  private

  def lesson_params
    params.require(:lesson).permit(:date, :location, :language_id, :student_id, :teacher_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @lesson = Lesson.find(params[:lesson_id])
    @review = Review.new
    @review.lesson = @lesson
    authorize(@review)
  end

  def create
    @review = Review.new(review_params)
    @lesson = Lesson.find(params[:lesson_id])
    @review.lesson = @lesson
    authorize(@review)
    if @review.save
      flash[:notice] = 'Your review is ready!'
      redirect_to users_dashboard_path
    else
      flash[:alert] = 'There was a problem with your review.'
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :lesson_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present? && params[:search][:language].present? && params[:search][:location].present?
      sql_query = "languages.id = :query"
      @teachers = policy_scope(User).joins(:languages).where(sql_query, query: "#{params[:search][:language]}").near(params[:search][:location], 100)
    elsif params[:search].present? && params[:search][:language].present?
      sql_query = "languages.id = :query"
      @teachers = policy_scope(User).joins(:languages).where(sql_query, query: "#{params[:search][:language]}")
    elsif params[:search].present? && params[:search][:location].present?
      @teachers = policy_scope(User).near(params[:search][:location], 100)
    else
      @teachers = policy_scope(User)
    end
    @languages = Language.all

    @markers = @teachers.map do |teacher|
      {
        lat: teacher.latitude,
        lng: teacher.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { teacher: teacher }),
        image_url: helpers.asset_url('pin.png')
      }
    end
  end

  def show
    @teacher = User.find(params[:id])
    authorize @teacher
    @lesson = Lesson.new
    @user = current_user ? current_user : User.new
  end

  def dashboard
    @user = current_user
    authorize @user
  end

  def edit
    authorize(User.find(params[:id]))
    @user = User.find(params[:id])
  end

  def update
    authorize(User.find(params[:id]))
    @user = User.find(params[:id])
    @user.update(user_params)

    current_user.language_skills.destroy_all
    params[:user][:languages].each do |language|
      LanguageSkill.create(user_id: @user.id, language_id: language)
    end

    current_user.user_qualifications.destroy_all
    if !params[:user][:qualifications].nil?
      params[:user][:qualifications].each do |qualification|
        UserQualification.create(user_id: @user.id, qualification_id: qualification)
      end
    end

    redirect_to users_dashboard_path
  end

  private

  def user_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:user).permit(:first_name, :last_name, :email, :gender, :age, :phone_number, :location, :availability, :biography, :is_teacher, :languages, :qualifications, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="https://res.cloudinary.com/dhkin63b7/image/upload/v1583375534/jRNLD_ly7t7u.png">
    <title>Lingua | Find a local language tutor</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/reviews/new.html.erb
<body>
  <div class="review-background">
    <div class='container'>
      <div class="log-form">
        <h1 class="text-center">Post a New Review</h1>
        <%= simple_form_for [@lesson, @review] do |f| %>

        <%= f.input :content, input_html: { class: 'form-control' } %>
        <%= f.input :rating, input_html: { min: '0', max: '5', class: 'form-control' } %>
        <div class="teacher-buttons">
          <%= link_to "Back to Dashboard", users_dashboard_path, class: "btn btn-ghost" %>
          <%= f.submit "Add a Review", class: "btn btn-black" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_rating-stars.html.erb
<% 5.times do |num| %>
  <i class="fa<%= rating > num ? 's' : 'r' %> fa-star review-star"></i>
<% end %>

app/views/users/_info_window.html.erb
<div class="info-window container">
  <h6><%= link_to "#{teacher.first_name} #{teacher.last_name}", "/users/#{teacher.id}" %></h6>
  <p class="map-location"><%= teacher.location %></p>
    <div class="map-languages">
      <% if teacher.languages.empty? %>
      <%= image_tag 'flags/ca.png', class: "flag-small" %>
      <% else %>
      <% teacher.languages.each do |language|   %>
      <%= image_tag language.flag, class: "flag-small" %>
      <% end %>
      <% end %>
    </div>
</div>

app/views/users/_status.html.erb
<div class="tab-pane fade show <%= state == 'confirmed' ? 'active' : '' %>" id="pills-<%= state %>" role="tabpanel" aria-labelledby="pills-<%= state %>-tab">
  <div class="table-wrapper-scroll-y my-custom-scrollbar">
  <table>
    <thead>
      <tr>
        <th>Language</th>
        <th>Teacher</th>
        <th>Date</th>
        <th>Location</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.language.name %></td>
          <td><%= lesson.teacher.first_name %> <%= lesson.teacher.last_name %></td>
          <td><%= lesson.date.strftime("%b %e, %l:%M hs") %></td>
          <td><%= lesson.location %></td>

          <% case state %>
          <% when "confirmed" %>
            <td><%= link_to "Cancel", lesson_path(lesson, lesson: { status: "cancelled" }), method: :patch, class: "btn btn-ghost" %></td>
          <% when "pending" %>
            <% if @user.is_teacher %>
              <td><%= link_to "Confirm", lesson_path(lesson, lesson: { status: "confirmed" }), method: :patch, class: "btn btn-success" %></td>
              <td><%= link_to "Cancel", lesson_path(lesson, lesson: { status: "cancelled" }), method: :patch, class: "btn btn-ghost" %></td>
            <% else %>
              <td><%= link_to "Cancel", lesson_path(lesson, lesson: { status: "cancelled" }), method: :patch, class: "btn btn-ghost" %></td>
            <% end %>
          <% when "completed" %>
            <% if @user.is_teacher %>
                <td><%= link_to "Delete", lesson_path(lesson), method: :delete, class: "btn btn-ghost " %></td>
            <% elsif lesson.reviews.first.nil? %>
                <td><%= link_to "Review", new_lesson_review_path(lesson), class: "btn btn-ghost" %></td>
            <% else %>
                <td><div class="btn no">Reviewed!</div></td>
            <% end %>
          <% else %>
              <td><%= link_to "Delete", lesson_path(lesson), method: :delete, class: "btn btn-ghost" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard-body">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon-white">
    <%= link_to "/", class: "navbar-brand" do %>
      <span class="nav-item logo logo-black">Lingua</span>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Search classes", "/", class: "nav-link nav-item-black" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown d-flex align-content-center">
            <div class="d-flex align-items-center">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://www.tuktukdesign.com/wp-content/uploads/2020/01/profile-icon-vector.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My account", users_dashboard_path, class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
          </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", "/users/sign_in", class: "nav-link nav-item-black" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", "/users/sign_up", class: "nav-link nav-item-black" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container-fluid">
    <div class="card-category-dashboard">
      <h2 class="text-center">My Account</h2>
      <div class="profile row">
        <div class="profile-info col-lg-4 col-md-12 col-sm-12">
          <div class="icon-container">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, height: 500, width: 400, crop: :fill, class: "icon" %>
            <% else %>
              <%= image_tag 'default-avatar.svg', class: "icon" %>
            <% end %>
          </div>
          <div class="profile-info-list">
            <div class="name">
              <b><%= @user.first_name %> <%= @user.last_name %></b>
            </div>
            <div class="contact">
              <i class="fas fa-envelope-square"></i> <%= @user.email %> | <i class="fas fa-phone-square"></i> <%= @user.phone_number %>
            </div>
            <br>
            <br>
          </div>
          <div class="biography-dash">
            <b>My Biography</b>
            <p><em><%= @user.biography %></em></p>
          </div>
          <br>
          <div class="flags-dash">
            <% if @user.languages.empty? %>
              <%= image_tag 'flags/ca.png', class: "teacher-flag" %>
            <% else %>
              <% @user.languages.each do |language|   %>
              <%= image_tag language.flag, class: "teacher-flag" %>
              <% end %>
            <% end %>
          </div>
          <br>
          <div class="text-center">
            <%= link_to "Edit profile", edit_user_path(@user.id), class: "btn btn-ghost" %>
          </div>
        </div>

        <div class="profile-classes col-lg-7 col-md-12 col-sm-12", style="overflow-x:auto;">
          <ul class="nav nav-pills nav-fill mb-3" id="pills-tab" role="tablist">
            <% Lesson::STATE.each do |state| %>
              <li class="nav-item">
                <a class="nav-link <%= state == 'confirmed' ? 'active' : '' %>" id="pills-<%= state %>-tab" data-toggle="pill" href="#pills-<%= state %>" role="tab" aria-controls="pills-<%= state %>" aria-selected="true"><%= state.capitalize %> classes</a>
              </li>
            <% end %>
          </ul>
          <div class="tab-content" id="pills-tabContent">
            <% Lesson::STATE.each do |state| %>
              <% if @user.is_teacher %>
                <%= render "status", state: state, lessons: @user.commitments.select { |lesson| lesson.status == state } %>
              <% else %>
                <%= render "status", state: state, lessons: @user.lessons.select { |lesson| lesson.status == state } %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

        <div class="profile-resources">
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="update-body">
  <br>
  <div class='container'>
    <div class="log-form">
      <h1><b>Edit Your Information</b></h1>
      <%= simple_form_for [@user] do |f| %>
        <%= f.input :photo, as: :file %>
        <%= f.input :first_name, input_html: { class: 'form-control' } %>
        <%= f.input :last_name, input_html: { class: 'form-control' } %>
        <%= f.input :email, input_html: { class: 'form-control' } %>
        <%= f.input :phone_number, input_html: { class: 'form-control' } %>
        <%= f.input :age, input_html: { class: 'form-control' } %>
        <%= f.input :gender, input_html: { class: 'form-control' } %>
        <%= f.input :location, input_html: { class: 'form-control' } %>
        <%= f.input :availability, input_html: { class: 'form-control' } if @user.is_teacher %>
        <%= f.input :biography, input_html: { class: 'form-control' } %>
        <%= f.input :languages, collection: Language.all, input_html: { multiple: true }, selected: current_user.languages.map { |l| l.id } %>
        <%= f.input :qualifications, collection: Qualification.all, input_html: { multiple: true }, selected: current_user.qualifications.map { |q| q.id } if @user.is_teacher %>
        <%= f.input :is_teacher,
            :as => :select,
            :collection => [['Yes',true],['No',false]],
            :include_blank => false,
            :label => "Register as a teacher?" %>
        <%= f.button :submit, class: "btn btn-black" %>
      <% end %>
      <%= link_to "Back", users_dashboard_path, class: 'btn btn-ghost' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon scroll">
  <%= link_to "/", class: "navbar-brand" do %>
  <span class="nav-item logo scroll">Lingua</span>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Search classes", "/", class: "nav-link scroll" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown d-flex align-content-center">
        <div class="d-flex align-items-center">
          <%if @current_user.photo.attached? %>
          <%= cl_image_tag @current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "https://www.tuktukdesign.com/wp-content/uploads/2020/01/profile-icon-vector.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My account", users_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </div>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log in", "/users/sign_in", class: "nav-link scroll" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", "/users/sign_up", class: "nav-link scroll" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="banner d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1489348611450-4c0d746d949b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80');">
  <div class="container">
    <p class="text-center">
      <span id="banner-typed-text"></span>
    </p>
    <div class="row justify-content-center">
      <div class="col-8 col-md-6 px-0">
        <%= simple_form_for :search, url: root_path, method: "GET", html: { class: '' } do |f| %>
        <div>
          <%= f.input :language, as: :select, collection: @languages, prompt: 'Select language', label: false, class: "" %>
          <%= f.input :location, place: 'Location', label: false, placeholder: "Enter location", class: "location-input", input_html: { class: 'auto-address' } %>
          <%= f.submit "Search", class: "btn btn-white btn-lg btn-search-home w-100 btn-sm btn-red" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mx-0 mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10">
      <div class="cards">
        <% @teachers.shuffle.each do |teacher| %>
        <div class="card-category mb-3 py-3">
          <div class="d-flex justify-content-center">
            <% if teacher.photo.attached? %>
            <%= cl_image_tag teacher.photo.key, height: 500, width: 400, crop: :fill, class: "icon" %>
            <% else %>
            <%= image_tag 'default-avatar.svg', class: "icon" %>
            <% end %>
          </div>
          <div class="name">
            <p><%= teacher.first_name %> <%= teacher.last_name %></p>
          </div>
          <div class="languages">
            <% if teacher.languages.empty? %>
            <%= image_tag 'flags/ca.png', class: "flag" %>
            <% else %>
            <% teacher.languages.each do |language|   %>
            <%= image_tag language.flag, class: "flag" %>
            <% end %>
            <% end %>
          </div>
          <div class="qualifications">
            <p><b>Availability:</b> <%= teacher.availability.capitalize %></p>
          </div>
          <div class="location">
            <p><em><%= teacher.location %></em></p>
          </div>
          <div class="text-center">
            <%= link_to "View profile", "/users/#{teacher.id}", class: "btn btn-ghost" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4 col-md-12 col-12 px-0">
      <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
</div>
</div>